config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :videos, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :category

  mount_uploader :file, VideoUploader

  validates :title, :file, presence: true

  validate :file_size

  def file_size
    errors.add :file, message: "should be less than 200MB" if file && file.size > 200.megabytes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @category = Category.find_by(id: params[:category_id])
    if @category
      @videos = @category.videos.order(:created_at)
    else
      @videos = Video.all.order(:created_at)
    end

    respond_to do |format|
      format.js { render :js => "window.location='#{ root_path(category_id: @category&.id) }'" }
      format.html { render :index }
    end

  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    redirect_to root_path
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to root_path
    else
      flash[:alert] = @video.errors&.full_messages&.join(" ")
      render :new
    end
  end

  private

  def video_params
    params.require(:video).permit(:title, :file, :category_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def categories_filter
    [["All", "all"]] + Category.all.pluck(:name, :id)
  end
end

app/helpers/videos_helper.rb
module VideosHelper
  def categories
    Category.all.pluck(:name, :id)
  end
end

app/views/home/index.html.erb
<div class="btn-container">
  <div style="display: flex; margin-bottom: 15px; justify-content: flex-end">
    <label class="select-categories-filter"> Category: </label>
    <%= select_tag :category_id, options_for_select(categories_filter, @category&.id), id: "category_change",
        class: 'form-control browser-default filter-input select-category',
        data: { url: root_path } %>
    <%= link_to new_video_path, :class => "btn btn-primary" do %>
      Upload New
    <% end %>      
  </div>

</div>

<div class="content-container">
  <div class="row">
    <% @videos.each do |video| %>
        <div class="column card">
          <%= video_tag video.file.url, :size => "320x240", poster: video.file.thumb.url, title: video.title, :controls => true, :class => "video" %>
          <div class="video-info">
            <p class="category"> <%= video.category.name %></p>
            <p class="text"> <%= video.title %> </p>
          </div>
        </div>
    <% end %>
    </div>
</div>

<script>
    $('#category_change').click(function(event) {
      var category = $('#category_change').val();
      var data_url =  $(this).data('url');
      $.ajax({
          type: "GET",
          url: data_url ,
          data: {category_id: category},
          success: function() {
          }
      });
    });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyVideo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="header">
    <h1 class="pro-name">MyVideo</h1>
  </div>
    <%= yield %>
  </body>
</html>

app/views/videos/new.html.erb
<div class="content-container">
    <div>
        <h4> Add New Video</h4>
    </div>

    <div class="row">
        <div class="new-card col" >
            <%= form_with( model: @video, url: videos_path, method: 'POST', local: true) do |f| %>
              <div class="col">
                  <div class="form-container">
                    <div class="form-group">
                        <label class="col-sm-2 col-md-2 control-label">Category:</label>
                        <div class="col-sm-10 col-md-8">
                            <%= f.select :category_id, categories, {:prompt => "Select Video Category"}, {required: 'true', class: 'select-category'}%>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 col-md-2 control-label">Title:</label>
                        <div class="col-sm-10 col-md-8">
                            <%= f.text_field :title, class: "form-control hidden", placeholder: "Title for Video", required: true %>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 col-md-2 control-label">Upload File:</label>
                        <div class="col-sm-10 col-md-8">
                            <%= f.file_field :file, class: "form-control hidden", accept: '.mp4, .mov, .webm', required: true%>
                        </div>
                    </div>
              </div>

              <div class="form-group form-actions" style="padding: 30px 0px">
                  <% flash.each do |type, msg| %><div class="error-msg"><%= msg %></div><% end %>
                  <div>
                      <%= f.submit 'Save details', class: "btn btn-primary" %>
                      <%= link_to videos_path, :class => "btn btn-outlined" do %>
                          <% 'Cancel' %>
                      <% end %>
                  </div>
              </div>
              </div>
            <% end %>
      </div>
</div>